// src/page/auth.vue
<template>
  <div class="page-container"></div>
</template>
<script>
  import { Indicator } from 'mint-ui';
  import { wxAuth4Public } from 'pms-saas-common/lib/util/wx'
  import { urlParams, object2Url } from 'pms-saas-common/lib/util/object'
  import { WX_APP_ID } from '@util/const'

  export default {
    data() {
      return {}
    },
    mounted() {
      Indicator.open('微信授权')

      this.init()
    },
    methods: {
      init() {
        const search = urlParams(window.location.href)
        const params = new URLSearchParams(search)
        const code = params.get('code')

        if (code) {

        } else {
          this.handleAuth()
        }
      },
      handleAuth() {
        const url = 'https://open.weixin.qq.com/connect/oauth2/authorize'
        const redirectUrl = window.location.href.split('?')[0]
        const authParams = wxAuth4Public(WX_APP_ID, redirectUrl, 'userInfo')

        // window.location.replace(`${ url }?${ object2Url(authParams) }#wechat_redirect`)
        console.log(`${ url }?${ object2Url(authParams) }#wechat_redirect`)
      }
    }
  }
</script>

// src/pages/Auth.jsx
import React, { PureComponent } from 'react'
import { inject, observer } from 'mobx-react'
import { Toast } from 'antd-mobile'
import { urlParams, object2Url, wxAuth4Public } from 'pms-saas-common'
import { WX_APP_ID } from '@utils/const'
import { setWxUserInfo } from '../utils/cache'
import { BASE_PATH } from '../utils/const'

@inject(
  'WxModel',
)
@observer
class AuthPage extends PureComponent {
  componentDidMount() {
    this.init()
  }

  init() {
    Toast.loading('微信授权中', 10)

    const search = urlParams(window.location.href)
    /* eslint-disable-next-line */
    const params = new URLSearchParams(search)
    const code = params.get('code')

    if (code) {
      this.handleCode(code)
    } else {
      this.handleAuth()
    }
  }

  handleAuth = () => {
    const appId = WX_APP_ID
    const url = 'https://open.weixin.qq.com/connect/oauth2/authorize'
    const redirectUrl = window.location.href.split('?')[0]
    const authParams = wxAuth4Public(appId, redirectUrl, 'userInfo')
    
    window.location.replace(`${ url }?${ object2Url(authParams) }#wechat_redirect`)
    // console.log(`${ url }?${ object2Url(authParams) }#wechat_redirect`)
  }

  handleCode = async code => {
    const { WxModel, history } = this.props
    const { getWxUserInfoByCode } = WxModel

    const wxUserInfo = await getWxUserInfoByCode({ code })

    if (wxUserInfo) {
      setWxUserInfo(wxUserInfo)

      history.replace(`${ BASE_PATH }/home`)
    }
  }

  render() {
    return (
      <div className='page-container' />
    )
  }
}

export default AuthPage
